### PR TITLE
Update SmartBone to use new vector library

### PR DESCRIPTION
**Pull request by Ramdoys**
*yes I did do this on my main branch, fight me (it was an accident)*

Changes all Vector3 usage - for applicable functions & constants - to the newly added vector library.
I forgot to disable my StyLua, so a bunch of files got formatted in the process, hope it's not a big deal! You can always just change those back if they're that important.

### CODE REVIEW

**Comment by Ramdoys** [comment]
I would like to note that there are some issues with the fields for the vector library right now, so type errors may appear. They'll be coming soon though hopefully.

**Comment by JakeyWasTaken** [comment]
I think for the vector library to be a worthwhile change in its current state, we would have to make use of the new vector globals dot, magnitude, normalize and cross as they're considerably more performant.

**Comment by JakeyWasTaken** [comment]
If you could close this pr, make a seperate one that affects a new branch for vector-lib then I'd be willing to merge it and go through those global changes myself

**Comment by Ramdoys** [comment]
Will do! And don't worry about those global changes, I can look for them myself right now.

**Pull request closed without merging**
