### PR TITLE
perf: update to new vector library

### PR DESCRIPTION
**Pull request by Ramdoys**
The upgrade is complete!

Took me about 2 days to complete this roughly 2 hour process (lots of distractions). A lot of the new library methods are amazing.

I benchmarked and noticed there is no reason to locally cache library functions as they serve no benefit to performance (and in some cases hurt it), thus why I did not for any. Vector library constants, however, prove to serve a bit of performance help -- but negligible. Just wanted to mention this if it is helpful in any case.

I did not test **ANY OF THIS** in Roblox, so please do, but I am more than confident everything looks fine, though you can look at the diffs (they are quite long) if you are worried. Of course test this in Roblox whenever the chance appears -- I know I will.

It could be good to look into more utilization of the vector library like `vector.floor`, `vector.abs`, `vector.sign`, etc., but I don't know if they have any uses within SmartBone, although I'm almost certain they have uses somewhere.

### CODE REVIEW

**Comment by JakeyWasTaken** [comment]
I'm not too knowledgeable on how PR's from a fork work, but if you could make this PR target a separate branch in the main repo that would be great, I'm just getting off now so I won't be able to review until later tommorow- though I had a quick look over and everything looks fine

**Comment by Ramdoys** [comment]
> I'm not too knowledgeable on how PR's from a fork work, but if you could make this PR target a separate branch in the main repo that would be great, I'm just getting off now so I won't be able to review until later tommorow- though I had a quick look over and everything looks fine

You'll have to create a branch under this repository named 'vector-lib' or something like that! I cannot create branches to target for my PR if they don't exist.

**Comment by Ramdoys** [comment]
I converted this to a draft, I still need to fix some things with this PR.

**Comment by JakeyWasTaken** [comment]
@Ramdoys ive created the branch for you

**Comment by Ramdoys** [comment]
Changed target branch to `vector-lib`.

**Comment by Ramdoys** [comment]
I tested this build and it appears to work completely fine with no errors or changes with how it works.

**Comment by JakeyWasTaken** [comment]
I think the types referring to Vector3's should be changed to vectors

**Comment by Ramdoys** [comment]
I will do that once I am home - thank you for letting me know. I completely overlooked that!

**Comment by Ramdoys** [comment]
@JakeyWasTaken Ended up just doing it on my school laptop. Let me know if everything looks good. I didn't change it for documentation to avoid confusion.

**Review by JakeyWasTaken — APPROVED** [review]
This looks good to me, im gonna merge

**Pull request merged**
